language: node_js
node_js:
- 18
env:
  global:
    secure: BAtxWndrxg7cDoNEUgrL19kXnOq/n1Zi5mplpWXlZN9+sMsyT8A0YKtxnAOr5Wg1FPty1ay5OFXZV8bNOvhyOQQw7ip5WBMd89eBNS54KES7xCucaEPXDxzkHl3p/nB5gsqq8mueAam2mcLRwdTMLP57ZmBDHIuL0neCaP4EvrUwqWL8uhurLzChuVB8rR9Bgyf0upqxaS1UhMsuFq2uMe0OQhvY9YlrVd0C0qjC/+fvRNq+pE8ntG/C9NK/usfce4yNIB1GB59aSglBMvZDtTCqQcsUvyEXADbstrlqFslpRKOecr4daqMZ05WlQkjjyLhmRtZ0/9hc6VR8wdflksgWazK1lWUt7nu+YO2kNMVMw9FAFlwTpL44H9drQ537g3DIadNxct77Qo58hbYfZoA4s3vALv8yW6NlMRO0qPK7zXkAS/Aopeh7knktMi4m5T3VTrT/yOs2HCHEsNnjqoqDNrI+Ge/Xdx7v2jR6aL5DffOsv9gHFI/vU2CSqR7J1MSoZrpeavBaKKFBhTxQvHsvRrLH8U/h2WevnB0x5Pp3wZpxYEgT6vH4qXRRoWwu93DZAqGWgXKmjyBpv8qzqkDVQIFcUwhVShWvkLXoF5zQQAxLpbfhxcBfgquka8GEi/rnhZxwUzalS0UAX2Hds5NNQisNgq4ZYe66ibMQhRE=
